name: lint

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Format with Prettier
        uses: creyD/prettier_action@v4.3
        with:
          commit_message: Format code with Prettier
